/**
 * Generates every NomadVNC app icon from `branding/logo.svg`.
 *
 * Run with `pnpm icons` (repo root) or `pnpm --filter @nomadvnc/desktop
 * generate:icons`. Renders HTML in an offscreen Electron window so the
 * mono logo can be tinted with CSS and edges keep real transparency.
 *
 * Outputs:
 *   apps/desktop/build/icon.{png,ico,icns}, build/icons/icon-<size>.png
 *     (gitignored; regenerated by the package scripts)
 *   apps/mobile/android/.../res/mipmap-<density>/ic_launcher{,_round,_foreground,_monochrome}.png
 *   apps/mobile/ios/NomadVNC/Images.xcassets/AppIcon.appiconset/AppIcon-1024.png
 *     (committed — rerun after changing the logo)
 */
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const zlib = require("node:zlib");
const { app, BrowserWindow } = require("electron");

const desktopRoot = path.resolve(__dirname, "..");
const workspaceRoot = path.resolve(desktopRoot, "../..");
const logoPath = path.join(workspaceRoot, "branding", "logo.svg");
const desktopBuild = path.join(desktopRoot, "build");
const androidRes = path.join(workspaceRoot, "apps/mobile/android/app/src/main/res");
const iosAppIcon = path.join(workspaceRoot, "apps/mobile/ios/NomadVNC/Images.xcassets/AppIcon.appiconset");

const CANVAS = 1024;
const INK = "#133c4e";
const TILE_BACKGROUND = "linear-gradient(145deg, #ffffff 0%, #f0f5fc 58%, #e6eef8 100%)";
const GLOW =
  "radial-gradient(circle at 24% 18%, rgba(151, 156, 242, 0.16), transparent 26%)," +
  "radial-gradient(circle at 78% 76%, rgba(19, 60, 78, 0.08), transparent 28%)";

/**
 * Icon variants. `tile` draws the branded background in a shape; `logo`
 * is the logo's size as a fraction of the canvas.
 * - desktop: rounded tile with transparent margins (macOS/Windows/Linux)
 * - square: full-bleed, opaque (iOS masks it itself)
 * - round: circle (Android legacy round icon)
 * - foreground: logo only, inside Android's adaptive-icon safe zone
 * - monochrome: same, for Android 13 themed icons (only alpha is used)
 */
const VARIANTS = {
  desktop: { tile: "rounded", logo: 0.66 },
  square: { tile: "square", logo: 0.68 },
  round: { tile: "circle", logo: 0.6 },
  foreground: { tile: null, logo: 0.57 },
  monochrome: { tile: null, logo: 0.57, ink: "#ffffff" },
};

function variantHtml(logoDataUrl, variant) {
  const { tile, logo, ink = INK } = variant;
  const tileCss =
    tile === "rounded"
      ? "width: 84%; height: 84%; border-radius: 21%; box-shadow: 0 2% 4% rgba(17, 37, 53, 0.18);"
      : tile === "circle"
        ? "width: 92%; height: 92%; border-radius: 50%; box-shadow: 0 1.5% 3% rgba(17, 37, 53, 0.16);"
        : tile === "square"
          ? "width: 100%; height: 100%;"
          : "width: 100%; height: 100%; background: transparent !important;";
  return `<!doctype html>
<html><head><meta charset="utf-8" /><style>
  html, body { margin: 0; width: ${CANVAS}px; height: ${CANVAS}px; overflow: hidden; background: transparent; }
  body { display: grid; place-items: center; }
  .tile { ${tileCss} display: grid; place-items: center; position: relative; overflow: hidden;
          background: ${GLOW}, ${TILE_BACKGROUND}; }
  .logo { width: ${Math.round(logo * CANVAS)}px; height: ${Math.round(logo * CANVAS)}px; background: ${ink};
          mask: url("${logoDataUrl}") center / contain no-repeat;
          -webkit-mask: url("${logoDataUrl}") center / contain no-repeat; }
</style></head>
<body><div class="tile"><div class="logo"></div></div></body></html>`;
}

/** Renders one variant offscreen (keeps transparency) and returns a 1024px NativeImage. */
async function render(logoDataUrl, variant) {
  const window = new BrowserWindow({
    width: CANVAS,
    height: CANVAS,
    show: false,
    frame: false,
    transparent: true,
    backgroundColor: "#00000000",
    webPreferences: { offscreen: true },
  });
  try {
    const painted = new Promise((resolve) => {
      let frames = 0;
      window.webContents.on("paint", (_event, _dirty, image) => {
        // Skip the first frames so the mask image has decoded.
        if (++frames >= 3) resolve(image);
      });
    });
    window.webContents.setFrameRate(30);
    // A temp file, not a data: URL — the inlined logo makes the page too
    // large for data URLs to load reliably.
    const page = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "nomadvnc-icon-")), "icon.html");
    fs.writeFileSync(page, variantHtml(logoDataUrl, variant));
    await window.loadFile(page);
    window.webContents.invalidate();
    const image = await Promise.race([
      painted,
      new Promise((_, reject) => setTimeout(() => reject(new Error("offscreen render timed out")), 10_000)),
    ]);
    return image.resize({ width: CANVAS, height: CANVAS, quality: "best" });
  } finally {
    window.destroy();
  }
}

const sized = (image, size) => image.resize({ width: size, height: size, quality: "best" }).toPNG();

function write(file, buffer) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, buffer);
}

function createIco(entries) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(entries.length, 4);
  const directory = [];
  const payload = [];
  let offset = 6 + 16 * entries.length;
  for (const entry of entries) {
    const dir = Buffer.alloc(16);
    dir.writeUInt8(entry.size >= 256 ? 0 : entry.size, 0);
    dir.writeUInt8(entry.size >= 256 ? 0 : entry.size, 1);
    dir.writeUInt16LE(1, 4);
    dir.writeUInt16LE(32, 6);
    dir.writeUInt32LE(entry.buffer.length, 8);
    dir.writeUInt32LE(offset, 12);
    offset += entry.buffer.length;
    directory.push(dir);
    payload.push(entry.buffer);
  }
  return Buffer.concat([header, ...directory, ...payload]);
}

/** Apple .icns with PNG payloads (icp4/5/6 = 16/32/64, ic07–ic10 = 128–1024). */
function createIcns(entries) {
  const chunks = [];
  let total = 8;
  for (const entry of entries) {
    const header = Buffer.alloc(8);
    header.write(entry.type, 0, 4, "ascii");
    header.writeUInt32BE(8 + entry.buffer.length, 4);
    chunks.push(header, entry.buffer);
    total += 8 + entry.buffer.length;
  }
  const fileHeader = Buffer.alloc(8);
  fileHeader.write("icns", 0, 4, "ascii");
  fileHeader.writeUInt32BE(total, 4);
  return Buffer.concat([fileHeader, ...chunks]);
}

function writeDesktop(desktop) {
  const sizes = [1024, 512, 256, 128, 64, 48, 32, 16];
  const bySize = new Map(sizes.map((size) => [size, sized(desktop, size)]));
  for (const [size, buffer] of bySize) {
    write(path.join(desktopBuild, "icons", `icon-${size}.png`), buffer);
  }
  write(path.join(desktopBuild, "icon.png"), bySize.get(512));
  write(
    path.join(desktopBuild, "icon.ico"),
    createIco([256, 128, 64, 48, 32, 16].map((size) => ({ size, buffer: bySize.get(size) }))),
  );
  write(
    path.join(desktopBuild, "icon.icns"),
    createIcns([
      { type: "icp4", buffer: bySize.get(16) },
      { type: "icp5", buffer: bySize.get(32) },
      { type: "icp6", buffer: bySize.get(64) },
      { type: "ic07", buffer: bySize.get(128) },
      { type: "ic08", buffer: bySize.get(256) },
      { type: "ic09", buffer: bySize.get(512) },
      { type: "ic10", buffer: bySize.get(1024) },
    ]),
  );
}

function writeAndroid(images) {
  // Launcher icons are 48dp; adaptive-icon layers are 108dp.
  const densities = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };
  for (const [density, scale] of Object.entries(densities)) {
    const dir = path.join(androidRes, `mipmap-${density}`);
    write(path.join(dir, "ic_launcher.png"), sized(images.desktop, 48 * scale));
    write(path.join(dir, "ic_launcher_round.png"), sized(images.round, 48 * scale));
    write(path.join(dir, "ic_launcher_foreground.png"), sized(images.foreground, 108 * scale));
    write(path.join(dir, "ic_launcher_monochrome.png"), sized(images.monochrome, 108 * scale));
  }
}

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function pngChunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

/**
 * Opaque RGB PNG (no alpha channel). The App Store rejects app icons with
 * an alpha channel even when every pixel is opaque, and Electron only
 * writes RGBA.
 */
function opaquePng(image) {
  const { width, height } = image.getSize();
  const bgra = image.toBitmap();
  const rows = Buffer.alloc(height * (1 + width * 3));
  for (let y = 0; y < height; y++) {
    const row = y * (1 + width * 3);
    rows[row] = 0; // filter: none
    for (let x = 0; x < width; x++) {
      const src = (y * width + x) * 4;
      const dst = row + 1 + x * 3;
      rows[dst] = bgra[src + 2];
      rows[dst + 1] = bgra[src + 1];
      rows[dst + 2] = bgra[src];
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // colour type: truecolour, no alpha
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", zlib.deflateSync(rows, { level: 9 })),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
}

function writeIos(square) {
  // A single 1024px universal icon; Xcode 14+ derives every size from it.
  write(path.join(iosAppIcon, "AppIcon-1024.png"), opaquePng(square.resize({ width: 1024, height: 1024 })));
  write(
    path.join(iosAppIcon, "Contents.json"),
    `${JSON.stringify(
      {
        images: [{ filename: "AppIcon-1024.png", idiom: "universal", platform: "ios", size: "1024x1024" }],
        info: { author: "xcode", version: 1 },
      },
      null,
      2,
    )}\n`,
  );
}

/** Packaging only needs the (gitignored) desktop icons; `pnpm icons` refreshes all. */
const desktopOnly = process.argv.includes("--desktop-only");

async function main() {
  const variantNames = desktopOnly ? ["desktop"] : Object.keys(VARIANTS);
  const logoDataUrl = `data:image/svg+xml;base64,${fs.readFileSync(logoPath).toString("base64")}`;
  const images = {};
  for (const name of variantNames) {
    images[name] = await render(logoDataUrl, VARIANTS[name]);
  }
  writeDesktop(images.desktop);
  if (desktopOnly) {
    console.log("Icons written: desktop build/");
    return;
  }
  writeAndroid(images);
  writeIos(images.square);
  console.log("Icons written: desktop build/, Android mipmaps, iOS AppIcon");
}

app.disableHardwareAcceleration();
// Each variant renders in its own short-lived window; without this, closing
// the first one would quit the app before the rest render.
app.on("window-all-closed", () => {});
app
  .whenReady()
  .then(main)
  .then(() => app.quit())
  .catch((error) => {
    console.error("Failed to generate NomadVNC icons", error);
    app.exit(1);
  });
